services:
    app:
        build:
            context: .
            args:
                DATABASE_URL: ${DATABASE_URL}
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: postgresql://postgres:password@db:5432/pcf-deploy
        depends_on:
            db:
                condition: service_healthy
            migrator:
                condition: service_completed_successfully
    migrator:
        build:
            context: .
            target: migrator
        environment:
            DATABASE_URL: postgresql://postgres:password@db:5432/pcf-deploy
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:18
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: pcf-deploy
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 2s
            timeout: 5s
            retries: 15
